// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: game/v1/game.proto

package gamev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputType int32

const (
	InputType_INPUT_UNSPECIFIED InputType = 0
	InputType_INPUT_LEFT        InputType = 1
	InputType_INPUT_RIGHT       InputType = 2
	InputType_INPUT_ROTATE_CW   InputType = 3
	InputType_INPUT_ROTATE_CCW  InputType = 4
	InputType_INPUT_SOFT_DROP   InputType = 5
	InputType_INPUT_HARD_DROP   InputType = 6
	InputType_INPUT_HOLD        InputType = 7
)

// Enum value maps for InputType.
var (
	InputType_name = map[int32]string{
		0: "INPUT_UNSPECIFIED",
		1: "INPUT_LEFT",
		2: "INPUT_RIGHT",
		3: "INPUT_ROTATE_CW",
		4: "INPUT_ROTATE_CCW",
		5: "INPUT_SOFT_DROP",
		6: "INPUT_HARD_DROP",
		7: "INPUT_HOLD",
	}
	InputType_value = map[string]int32{
		"INPUT_UNSPECIFIED": 0,
		"INPUT_LEFT":        1,
		"INPUT_RIGHT":       2,
		"INPUT_ROTATE_CW":   3,
		"INPUT_ROTATE_CCW":  4,
		"INPUT_SOFT_DROP":   5,
		"INPUT_HARD_DROP":   6,
		"INPUT_HOLD":        7,
	}
)

func (x InputType) Enum() *InputType {
	p := new(InputType)
	*p = x
	return p
}

func (x InputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InputType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[0].Descriptor()
}

func (InputType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[0]
}

func (x InputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InputType.Descriptor instead.
func (InputType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{0}
}

type PieceType int32

const (
	PieceType_PIECE_UNSPECIFIED PieceType = 0
	PieceType_PIECE_I           PieceType = 1
	PieceType_PIECE_O           PieceType = 2
	PieceType_PIECE_T           PieceType = 3
	PieceType_PIECE_S           PieceType = 4
	PieceType_PIECE_Z           PieceType = 5
	PieceType_PIECE_J           PieceType = 6
	PieceType_PIECE_L           PieceType = 7
	PieceType_PIECE_GARBAGE     PieceType = 8
)

// Enum value maps for PieceType.
var (
	PieceType_name = map[int32]string{
		0: "PIECE_UNSPECIFIED",
		1: "PIECE_I",
		2: "PIECE_O",
		3: "PIECE_T",
		4: "PIECE_S",
		5: "PIECE_Z",
		6: "PIECE_J",
		7: "PIECE_L",
		8: "PIECE_GARBAGE",
	}
	PieceType_value = map[string]int32{
		"PIECE_UNSPECIFIED": 0,
		"PIECE_I":           1,
		"PIECE_O":           2,
		"PIECE_T":           3,
		"PIECE_S":           4,
		"PIECE_Z":           5,
		"PIECE_J":           6,
		"PIECE_L":           7,
		"PIECE_GARBAGE":     8,
	}
)

func (x PieceType) Enum() *PieceType {
	p := new(PieceType)
	*p = x
	return p
}

func (x PieceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PieceType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[1].Descriptor()
}

func (PieceType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[1]
}

func (x PieceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PieceType.Descriptor instead.
func (PieceType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{1}
}

type EventType int32

const (
	EventType_EVENT_UNSPECIFIED      EventType = 0
	EventType_EVENT_MATCH_START      EventType = 1
	EventType_EVENT_GAME_OVER        EventType = 2
	EventType_EVENT_WINNER           EventType = 3
	EventType_EVENT_GARBAGE_RECEIVED EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_UNSPECIFIED",
		1: "EVENT_MATCH_START",
		2: "EVENT_GAME_OVER",
		3: "EVENT_WINNER",
		4: "EVENT_GARBAGE_RECEIVED",
	}
	EventType_value = map[string]int32{
		"EVENT_UNSPECIFIED":      0,
		"EVENT_MATCH_START":      1,
		"EVENT_GAME_OVER":        2,
		"EVENT_WINNER":           3,
		"EVENT_GARBAGE_RECEIVED": 4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_v1_game_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_game_v1_game_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{2}
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Join
	//	*ClientMessage_Input
	//	*ClientMessage_Ping
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_game_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetJoin() *JoinRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientMessage) GetInput() *InputRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *ClientMessage) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Join struct {
	Join *JoinRequest `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ClientMessage_Input struct {
	Input *InputRequest `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type ClientMessage_Ping struct {
	Ping *PingRequest `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*ClientMessage_Join) isClientMessage_Payload() {}

func (*ClientMessage_Input) isClientMessage_Payload() {}

func (*ClientMessage_Ping) isClientMessage_Payload() {}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_game_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *JoinRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type InputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceId    uint64                 `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	Input         InputType              `protobuf:"varint,2,opt,name=input,proto3,enum=game.v1.InputType" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputRequest) Reset() {
	*x = InputRequest{}
	mi := &file_game_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRequest) ProtoMessage() {}

func (x *InputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRequest.ProtoReflect.Descriptor instead.
func (*InputRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *InputRequest) GetSequenceId() uint64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *InputRequest) GetInput() InputType {
	if x != nil {
		return x.Input
	}
	return InputType_INPUT_UNSPECIFIED
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_game_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_State
	//	*ServerMessage_Event
	//	*ServerMessage_Pong
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_game_v1_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetState() *StateUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *ServerMessage) GetEvent() *GameEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ServerMessage) GetPong() *PongResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_State struct {
	State *StateUpdate `protobuf:"bytes,1,opt,name=state,proto3,oneof"`
}

type ServerMessage_Event struct {
	Event *GameEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type ServerMessage_Pong struct {
	Pong *PongResponse `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

func (*ServerMessage_State) isServerMessage_Payload() {}

func (*ServerMessage_Event) isServerMessage_Payload() {}

func (*ServerMessage_Pong) isServerMessage_Payload() {}

type StateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TickId        uint64                 `protobuf:"varint,1,opt,name=tick_id,json=tickId,proto3" json:"tick_id,omitempty"`
	Grid          []byte                 `protobuf:"bytes,2,opt,name=grid,proto3" json:"grid,omitempty"`
	CurrentPiece  *Piece                 `protobuf:"bytes,3,opt,name=current_piece,json=currentPiece,proto3" json:"current_piece,omitempty"`
	NextPieces    []PieceType            `protobuf:"varint,4,rep,packed,name=next_pieces,json=nextPieces,proto3,enum=game.v1.PieceType" json:"next_pieces,omitempty"`
	HeldPiece     PieceType              `protobuf:"varint,5,opt,name=held_piece,json=heldPiece,proto3,enum=game.v1.PieceType" json:"held_piece,omitempty"`
	Score         uint32                 `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	Level         uint32                 `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_game_v1_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{5}
}

func (x *StateUpdate) GetTickId() uint64 {
	if x != nil {
		return x.TickId
	}
	return 0
}

func (x *StateUpdate) GetGrid() []byte {
	if x != nil {
		return x.Grid
	}
	return nil
}

func (x *StateUpdate) GetCurrentPiece() *Piece {
	if x != nil {
		return x.CurrentPiece
	}
	return nil
}

func (x *StateUpdate) GetNextPieces() []PieceType {
	if x != nil {
		return x.NextPieces
	}
	return nil
}

func (x *StateUpdate) GetHeldPiece() PieceType {
	if x != nil {
		return x.HeldPiece
	}
	return PieceType_PIECE_UNSPECIFIED
}

func (x *StateUpdate) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *StateUpdate) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GameEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=game.v1.EventType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_game_v1_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_UNSPECIFIED
}

func (x *GameEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GameEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_game_v1_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{7}
}

func (x *PongResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Piece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PieceType              `protobuf:"varint,1,opt,name=type,proto3,enum=game.v1.PieceType" json:"type,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Rotation      int32                  `protobuf:"varint,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Piece) Reset() {
	*x = Piece{}
	mi := &file_game_v1_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Piece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Piece) ProtoMessage() {}

func (x *Piece) ProtoReflect() protoreflect.Message {
	mi := &file_game_v1_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Piece.ProtoReflect.Descriptor instead.
func (*Piece) Descriptor() ([]byte, []int) {
	return file_game_v1_game_proto_rawDescGZIP(), []int{8}
}

func (x *Piece) GetType() PieceType {
	if x != nil {
		return x.Type
	}
	return PieceType_PIECE_UNSPECIFIED
}

func (x *Piece) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Piece) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Piece) GetRotation() int32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

var File_game_v1_game_proto protoreflect.FileDescriptor

const file_game_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x12game/v1/game.proto\x12\agame.v1\"\xa1\x01\n" +
	"\rClientMessage\x12*\n" +
	"\x04join\x18\x01 \x01(\v2\x14.game.v1.JoinRequestH\x00R\x04join\x12-\n" +
	"\x05input\x18\x02 \x01(\v2\x15.game.v1.InputRequestH\x00R\x05input\x12*\n" +
	"\x04ping\x18\x03 \x01(\v2\x14.game.v1.PingRequestH\x00R\x04pingB\t\n" +
	"\apayload\">\n" +
	"\vJoinRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"Y\n" +
	"\fInputRequest\x12\x1f\n" +
	"\vsequence_id\x18\x01 \x01(\x04R\n" +
	"sequenceId\x12(\n" +
	"\x05input\x18\x02 \x01(\x0e2\x12.game.v1.InputTypeR\x05input\"+\n" +
	"\vPingRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xa1\x01\n" +
	"\rServerMessage\x12,\n" +
	"\x05state\x18\x01 \x01(\v2\x14.game.v1.StateUpdateH\x00R\x05state\x12*\n" +
	"\x05event\x18\x02 \x01(\v2\x12.game.v1.GameEventH\x00R\x05event\x12+\n" +
	"\x04pong\x18\x03 \x01(\v2\x15.game.v1.PongResponseH\x00R\x04pongB\t\n" +
	"\apayload\"\x83\x02\n" +
	"\vStateUpdate\x12\x17\n" +
	"\atick_id\x18\x01 \x01(\x04R\x06tickId\x12\x12\n" +
	"\x04grid\x18\x02 \x01(\fR\x04grid\x123\n" +
	"\rcurrent_piece\x18\x03 \x01(\v2\x0e.game.v1.PieceR\fcurrentPiece\x123\n" +
	"\vnext_pieces\x18\x04 \x03(\x0e2\x12.game.v1.PieceTypeR\n" +
	"nextPieces\x121\n" +
	"\n" +
	"held_piece\x18\x05 \x01(\x0e2\x12.game.v1.PieceTypeR\theldPiece\x12\x14\n" +
	"\x05score\x18\x06 \x01(\rR\x05score\x12\x14\n" +
	"\x05level\x18\a \x01(\rR\x05level\"\xc8\x01\n" +
	"\tGameEvent\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.game.v1.EventTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\bmetadata\x18\x03 \x03(\v2 .game.v1.GameEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\fPongResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"g\n" +
	"\x05Piece\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.game.v1.PieceTypeR\x04type\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x1a\n" +
	"\brotation\x18\x04 \x01(\x05R\brotation*\xa8\x01\n" +
	"\tInputType\x12\x15\n" +
	"\x11INPUT_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"INPUT_LEFT\x10\x01\x12\x0f\n" +
	"\vINPUT_RIGHT\x10\x02\x12\x13\n" +
	"\x0fINPUT_ROTATE_CW\x10\x03\x12\x14\n" +
	"\x10INPUT_ROTATE_CCW\x10\x04\x12\x13\n" +
	"\x0fINPUT_SOFT_DROP\x10\x05\x12\x13\n" +
	"\x0fINPUT_HARD_DROP\x10\x06\x12\x0e\n" +
	"\n" +
	"INPUT_HOLD\x10\a*\x90\x01\n" +
	"\tPieceType\x12\x15\n" +
	"\x11PIECE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPIECE_I\x10\x01\x12\v\n" +
	"\aPIECE_O\x10\x02\x12\v\n" +
	"\aPIECE_T\x10\x03\x12\v\n" +
	"\aPIECE_S\x10\x04\x12\v\n" +
	"\aPIECE_Z\x10\x05\x12\v\n" +
	"\aPIECE_J\x10\x06\x12\v\n" +
	"\aPIECE_L\x10\a\x12\x11\n" +
	"\rPIECE_GARBAGE\x10\b*|\n" +
	"\tEventType\x12\x15\n" +
	"\x11EVENT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_MATCH_START\x10\x01\x12\x13\n" +
	"\x0fEVENT_GAME_OVER\x10\x02\x12\x10\n" +
	"\fEVENT_WINNER\x10\x03\x12\x1a\n" +
	"\x16EVENT_GARBAGE_RECEIVED\x10\x042I\n" +
	"\vGameService\x12:\n" +
	"\x04Play\x12\x16.game.v1.ClientMessage\x1a\x16.game.v1.ServerMessage(\x010\x01B\x10Z\x0egame/v1;gamev1b\x06proto3"

var (
	file_game_v1_game_proto_rawDescOnce sync.Once
	file_game_v1_game_proto_rawDescData []byte
)

func file_game_v1_game_proto_rawDescGZIP() []byte {
	file_game_v1_game_proto_rawDescOnce.Do(func() {
		file_game_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_v1_game_proto_rawDesc), len(file_game_v1_game_proto_rawDesc)))
	})
	return file_game_v1_game_proto_rawDescData
}

var file_game_v1_game_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_game_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_game_v1_game_proto_goTypes = []any{
	(InputType)(0),        // 0: game.v1.InputType
	(PieceType)(0),        // 1: game.v1.PieceType
	(EventType)(0),        // 2: game.v1.EventType
	(*ClientMessage)(nil), // 3: game.v1.ClientMessage
	(*JoinRequest)(nil),   // 4: game.v1.JoinRequest
	(*InputRequest)(nil),  // 5: game.v1.InputRequest
	(*PingRequest)(nil),   // 6: game.v1.PingRequest
	(*ServerMessage)(nil), // 7: game.v1.ServerMessage
	(*StateUpdate)(nil),   // 8: game.v1.StateUpdate
	(*GameEvent)(nil),     // 9: game.v1.GameEvent
	(*PongResponse)(nil),  // 10: game.v1.PongResponse
	(*Piece)(nil),         // 11: game.v1.Piece
	nil,                   // 12: game.v1.GameEvent.MetadataEntry
}
var file_game_v1_game_proto_depIdxs = []int32{
	4,  // 0: game.v1.ClientMessage.join:type_name -> game.v1.JoinRequest
	5,  // 1: game.v1.ClientMessage.input:type_name -> game.v1.InputRequest
	6,  // 2: game.v1.ClientMessage.ping:type_name -> game.v1.PingRequest
	0,  // 3: game.v1.InputRequest.input:type_name -> game.v1.InputType
	8,  // 4: game.v1.ServerMessage.state:type_name -> game.v1.StateUpdate
	9,  // 5: game.v1.ServerMessage.event:type_name -> game.v1.GameEvent
	10, // 6: game.v1.ServerMessage.pong:type_name -> game.v1.PongResponse
	11, // 7: game.v1.StateUpdate.current_piece:type_name -> game.v1.Piece
	1,  // 8: game.v1.StateUpdate.next_pieces:type_name -> game.v1.PieceType
	1,  // 9: game.v1.StateUpdate.held_piece:type_name -> game.v1.PieceType
	2,  // 10: game.v1.GameEvent.type:type_name -> game.v1.EventType
	12, // 11: game.v1.GameEvent.metadata:type_name -> game.v1.GameEvent.MetadataEntry
	1,  // 12: game.v1.Piece.type:type_name -> game.v1.PieceType
	3,  // 13: game.v1.GameService.Play:input_type -> game.v1.ClientMessage
	7,  // 14: game.v1.GameService.Play:output_type -> game.v1.ServerMessage
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_game_v1_game_proto_init() }
func file_game_v1_game_proto_init() {
	if File_game_v1_game_proto != nil {
		return
	}
	file_game_v1_game_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Join)(nil),
		(*ClientMessage_Input)(nil),
		(*ClientMessage_Ping)(nil),
	}
	file_game_v1_game_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerMessage_State)(nil),
		(*ServerMessage_Event)(nil),
		(*ServerMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_v1_game_proto_rawDesc), len(file_game_v1_game_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_v1_game_proto_goTypes,
		DependencyIndexes: file_game_v1_game_proto_depIdxs,
		EnumInfos:         file_game_v1_game_proto_enumTypes,
		MessageInfos:      file_game_v1_game_proto_msgTypes,
	}.Build()
	File_game_v1_game_proto = out.File
	file_game_v1_game_proto_goTypes = nil
	file_game_v1_game_proto_depIdxs = nil
}
