// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: matchmaking/v1/matchmaking.proto

package matchmakingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchmakingService_CreateMatch_FullMethodName  = "/matchmaking.v1.MatchmakingService/CreateMatch"
	MatchmakingService_JoinByInvite_FullMethodName = "/matchmaking.v1.MatchmakingService/JoinByInvite"
	MatchmakingService_FindRandom_FullMethodName   = "/matchmaking.v1.MatchmakingService/FindRandom"
	MatchmakingService_GetMatchInfo_FullMethodName = "/matchmaking.v1.MatchmakingService/GetMatchInfo"
)

// MatchmakingServiceClient is the client API for MatchmakingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchmakingServiceClient interface {
	CreateMatch(ctx context.Context, in *CreateMatchRequest, opts ...grpc.CallOption) (*CreateMatchResponse, error)
	JoinByInvite(ctx context.Context, in *JoinByInviteRequest, opts ...grpc.CallOption) (*JoinByInviteResponse, error)
	FindRandom(ctx context.Context, in *FindRandomRequest, opts ...grpc.CallOption) (*FindRandomResponse, error)
	GetMatchInfo(ctx context.Context, in *GetMatchInfoRequest, opts ...grpc.CallOption) (*GetMatchInfoResponse, error)
}

type matchmakingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchmakingServiceClient(cc grpc.ClientConnInterface) MatchmakingServiceClient {
	return &matchmakingServiceClient{cc}
}

func (c *matchmakingServiceClient) CreateMatch(ctx context.Context, in *CreateMatchRequest, opts ...grpc.CallOption) (*CreateMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMatchResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_CreateMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingServiceClient) JoinByInvite(ctx context.Context, in *JoinByInviteRequest, opts ...grpc.CallOption) (*JoinByInviteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinByInviteResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_JoinByInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingServiceClient) FindRandom(ctx context.Context, in *FindRandomRequest, opts ...grpc.CallOption) (*FindRandomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindRandomResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_FindRandom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingServiceClient) GetMatchInfo(ctx context.Context, in *GetMatchInfoRequest, opts ...grpc.CallOption) (*GetMatchInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchInfoResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_GetMatchInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchmakingServiceServer is the server API for MatchmakingService service.
// All implementations must embed UnimplementedMatchmakingServiceServer
// for forward compatibility.
type MatchmakingServiceServer interface {
	CreateMatch(context.Context, *CreateMatchRequest) (*CreateMatchResponse, error)
	JoinByInvite(context.Context, *JoinByInviteRequest) (*JoinByInviteResponse, error)
	FindRandom(context.Context, *FindRandomRequest) (*FindRandomResponse, error)
	GetMatchInfo(context.Context, *GetMatchInfoRequest) (*GetMatchInfoResponse, error)
	mustEmbedUnimplementedMatchmakingServiceServer()
}

// UnimplementedMatchmakingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchmakingServiceServer struct{}

func (UnimplementedMatchmakingServiceServer) CreateMatch(context.Context, *CreateMatchRequest) (*CreateMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMatch not implemented")
}
func (UnimplementedMatchmakingServiceServer) JoinByInvite(context.Context, *JoinByInviteRequest) (*JoinByInviteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinByInvite not implemented")
}
func (UnimplementedMatchmakingServiceServer) FindRandom(context.Context, *FindRandomRequest) (*FindRandomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindRandom not implemented")
}
func (UnimplementedMatchmakingServiceServer) GetMatchInfo(context.Context, *GetMatchInfoRequest) (*GetMatchInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatchInfo not implemented")
}
func (UnimplementedMatchmakingServiceServer) mustEmbedUnimplementedMatchmakingServiceServer() {}
func (UnimplementedMatchmakingServiceServer) testEmbeddedByValue()                            {}

// UnsafeMatchmakingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchmakingServiceServer will
// result in compilation errors.
type UnsafeMatchmakingServiceServer interface {
	mustEmbedUnimplementedMatchmakingServiceServer()
}

func RegisterMatchmakingServiceServer(s grpc.ServiceRegistrar, srv MatchmakingServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchmakingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchmakingService_ServiceDesc, srv)
}

func _MatchmakingService_CreateMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).CreateMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_CreateMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).CreateMatch(ctx, req.(*CreateMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakingService_JoinByInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinByInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).JoinByInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_JoinByInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).JoinByInvite(ctx, req.(*JoinByInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakingService_FindRandom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRandomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).FindRandom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_FindRandom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).FindRandom(ctx, req.(*FindRandomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakingService_GetMatchInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).GetMatchInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_GetMatchInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).GetMatchInfo(ctx, req.(*GetMatchInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchmakingService_ServiceDesc is the grpc.ServiceDesc for MatchmakingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchmakingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matchmaking.v1.MatchmakingService",
	HandlerType: (*MatchmakingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMatch",
			Handler:    _MatchmakingService_CreateMatch_Handler,
		},
		{
			MethodName: "JoinByInvite",
			Handler:    _MatchmakingService_JoinByInvite_Handler,
		},
		{
			MethodName: "FindRandom",
			Handler:    _MatchmakingService_FindRandom_Handler,
		},
		{
			MethodName: "GetMatchInfo",
			Handler:    _MatchmakingService_GetMatchInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matchmaking/v1/matchmaking.proto",
}
