// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: matchmaking/v1/matchmaking.proto

package matchmakingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameMode int32

const (
	GameMode_GAME_MODE_UNSPECIFIED GameMode = 0
	GameMode_GAME_MODE_SOLO        GameMode = 1
	GameMode_GAME_MODE_ONE_VS_ONE  GameMode = 2
)

// Enum value maps for GameMode.
var (
	GameMode_name = map[int32]string{
		0: "GAME_MODE_UNSPECIFIED",
		1: "GAME_MODE_SOLO",
		2: "GAME_MODE_ONE_VS_ONE",
	}
	GameMode_value = map[string]int32{
		"GAME_MODE_UNSPECIFIED": 0,
		"GAME_MODE_SOLO":        1,
		"GAME_MODE_ONE_VS_ONE":  2,
	}
)

func (x GameMode) Enum() *GameMode {
	p := new(GameMode)
	*p = x
	return p
}

func (x GameMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameMode) Descriptor() protoreflect.EnumDescriptor {
	return file_matchmaking_v1_matchmaking_proto_enumTypes[0].Descriptor()
}

func (GameMode) Type() protoreflect.EnumType {
	return &file_matchmaking_v1_matchmaking_proto_enumTypes[0]
}

func (x GameMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameMode.Descriptor instead.
func (GameMode) EnumDescriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{0}
}

type MatchStatus int32

const (
	MatchStatus_MATCH_STATUS_UNSPECIFIED MatchStatus = 0
	MatchStatus_MATCH_STATUS_WAITING     MatchStatus = 1
	MatchStatus_MATCH_STATUS_READY       MatchStatus = 2
	MatchStatus_MATCH_STATUS_IN_PROGRESS MatchStatus = 3
	MatchStatus_MATCH_STATUS_FINISHED    MatchStatus = 4
)

// Enum value maps for MatchStatus.
var (
	MatchStatus_name = map[int32]string{
		0: "MATCH_STATUS_UNSPECIFIED",
		1: "MATCH_STATUS_WAITING",
		2: "MATCH_STATUS_READY",
		3: "MATCH_STATUS_IN_PROGRESS",
		4: "MATCH_STATUS_FINISHED",
	}
	MatchStatus_value = map[string]int32{
		"MATCH_STATUS_UNSPECIFIED": 0,
		"MATCH_STATUS_WAITING":     1,
		"MATCH_STATUS_READY":       2,
		"MATCH_STATUS_IN_PROGRESS": 3,
		"MATCH_STATUS_FINISHED":    4,
	}
)

func (x MatchStatus) Enum() *MatchStatus {
	p := new(MatchStatus)
	*p = x
	return p
}

func (x MatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_matchmaking_v1_matchmaking_proto_enumTypes[1].Descriptor()
}

func (MatchStatus) Type() protoreflect.EnumType {
	return &file_matchmaking_v1_matchmaking_proto_enumTypes[1]
}

func (x MatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStatus.Descriptor instead.
func (MatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{1}
}

type CreateMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          GameMode               `protobuf:"varint,1,opt,name=mode,proto3,enum=matchmaking.v1.GameMode" json:"mode,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMatchRequest) Reset() {
	*x = CreateMatchRequest{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMatchRequest) ProtoMessage() {}

func (x *CreateMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMatchRequest.ProtoReflect.Descriptor instead.
func (*CreateMatchRequest) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMatchRequest) GetMode() GameMode {
	if x != nil {
		return x.Mode
	}
	return GameMode_GAME_MODE_UNSPECIFIED
}

func (x *CreateMatchRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type CreateMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	InviteCode    string                 `protobuf:"bytes,2,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	InviteLink    string                 `protobuf:"bytes,3,opt,name=invite_link,json=inviteLink,proto3" json:"invite_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMatchResponse) Reset() {
	*x = CreateMatchResponse{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMatchResponse) ProtoMessage() {}

func (x *CreateMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMatchResponse.ProtoReflect.Descriptor instead.
func (*CreateMatchResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMatchResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *CreateMatchResponse) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *CreateMatchResponse) GetInviteLink() string {
	if x != nil {
		return x.InviteLink
	}
	return ""
}

type JoinByInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinByInviteRequest) Reset() {
	*x = JoinByInviteRequest{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinByInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinByInviteRequest) ProtoMessage() {}

func (x *JoinByInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinByInviteRequest.ProtoReflect.Descriptor instead.
func (*JoinByInviteRequest) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{2}
}

func (x *JoinByInviteRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *JoinByInviteRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type JoinByInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Status        MatchStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=matchmaking.v1.MatchStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinByInviteResponse) Reset() {
	*x = JoinByInviteResponse{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinByInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinByInviteResponse) ProtoMessage() {}

func (x *JoinByInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinByInviteResponse.ProtoReflect.Descriptor instead.
func (*JoinByInviteResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{3}
}

func (x *JoinByInviteResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *JoinByInviteResponse) GetStatus() MatchStatus {
	if x != nil {
		return x.Status
	}
	return MatchStatus_MATCH_STATUS_UNSPECIFIED
}

type FindRandomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          GameMode               `protobuf:"varint,1,opt,name=mode,proto3,enum=matchmaking.v1.GameMode" json:"mode,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRandomRequest) Reset() {
	*x = FindRandomRequest{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRandomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRandomRequest) ProtoMessage() {}

func (x *FindRandomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRandomRequest.ProtoReflect.Descriptor instead.
func (*FindRandomRequest) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{4}
}

func (x *FindRandomRequest) GetMode() GameMode {
	if x != nil {
		return x.Mode
	}
	return GameMode_GAME_MODE_UNSPECIFIED
}

func (x *FindRandomRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type FindRandomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Status        MatchStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=matchmaking.v1.MatchStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRandomResponse) Reset() {
	*x = FindRandomResponse{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRandomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRandomResponse) ProtoMessage() {}

func (x *FindRandomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRandomResponse.ProtoReflect.Descriptor instead.
func (*FindRandomResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{5}
}

func (x *FindRandomResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *FindRandomResponse) GetStatus() MatchStatus {
	if x != nil {
		return x.Status
	}
	return MatchStatus_MATCH_STATUS_UNSPECIFIED
}

type GetMatchInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchInfoRequest) Reset() {
	*x = GetMatchInfoRequest{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchInfoRequest) ProtoMessage() {}

func (x *GetMatchInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMatchInfoRequest) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{6}
}

func (x *GetMatchInfoRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type GetMatchInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Mode          GameMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=matchmaking.v1.GameMode" json:"mode,omitempty"`
	Players       []*Player              `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	Status        MatchStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=matchmaking.v1.MatchStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchInfoResponse) Reset() {
	*x = GetMatchInfoResponse{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchInfoResponse) ProtoMessage() {}

func (x *GetMatchInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchInfoResponse.ProtoReflect.Descriptor instead.
func (*GetMatchInfoResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{7}
}

func (x *GetMatchInfoResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *GetMatchInfoResponse) GetMode() GameMode {
	if x != nil {
		return x.Mode
	}
	return GameMode_GAME_MODE_UNSPECIFIED
}

func (x *GetMatchInfoResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GetMatchInfoResponse) GetStatus() MatchStatus {
	if x != nil {
		return x.Status
	}
	return MatchStatus_MATCH_STATUS_UNSPECIFIED
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{8}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

var File_matchmaking_v1_matchmaking_proto protoreflect.FileDescriptor

const file_matchmaking_v1_matchmaking_proto_rawDesc = "" +
	"\n" +
	" matchmaking/v1/matchmaking.proto\x12\x0ematchmaking.v1\"_\n" +
	"\x12CreateMatchRequest\x12,\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x18.matchmaking.v1.GameModeR\x04mode\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"r\n" +
	"\x13CreateMatchResponse\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1f\n" +
	"\vinvite_code\x18\x02 \x01(\tR\n" +
	"inviteCode\x12\x1f\n" +
	"\vinvite_link\x18\x03 \x01(\tR\n" +
	"inviteLink\"S\n" +
	"\x13JoinByInviteRequest\x12\x1f\n" +
	"\vinvite_code\x18\x01 \x01(\tR\n" +
	"inviteCode\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"f\n" +
	"\x14JoinByInviteResponse\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.matchmaking.v1.MatchStatusR\x06status\"^\n" +
	"\x11FindRandomRequest\x12,\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x18.matchmaking.v1.GameModeR\x04mode\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"d\n" +
	"\x12FindRandomResponse\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.matchmaking.v1.MatchStatusR\x06status\"0\n" +
	"\x13GetMatchInfoRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\"\xc6\x01\n" +
	"\x14GetMatchInfoResponse\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12,\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x18.matchmaking.v1.GameModeR\x04mode\x120\n" +
	"\aplayers\x18\x03 \x03(\v2\x16.matchmaking.v1.PlayerR\aplayers\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.matchmaking.v1.MatchStatusR\x06status\";\n" +
	"\x06Player\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready*S\n" +
	"\bGameMode\x12\x19\n" +
	"\x15GAME_MODE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eGAME_MODE_SOLO\x10\x01\x12\x18\n" +
	"\x14GAME_MODE_ONE_VS_ONE\x10\x02*\x96\x01\n" +
	"\vMatchStatus\x12\x1c\n" +
	"\x18MATCH_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MATCH_STATUS_WAITING\x10\x01\x12\x16\n" +
	"\x12MATCH_STATUS_READY\x10\x02\x12\x1c\n" +
	"\x18MATCH_STATUS_IN_PROGRESS\x10\x03\x12\x19\n" +
	"\x15MATCH_STATUS_FINISHED\x10\x042\xf7\x02\n" +
	"\x12MatchmakingService\x12V\n" +
	"\vCreateMatch\x12\".matchmaking.v1.CreateMatchRequest\x1a#.matchmaking.v1.CreateMatchResponse\x12Y\n" +
	"\fJoinByInvite\x12#.matchmaking.v1.JoinByInviteRequest\x1a$.matchmaking.v1.JoinByInviteResponse\x12S\n" +
	"\n" +
	"FindRandom\x12!.matchmaking.v1.FindRandomRequest\x1a\".matchmaking.v1.FindRandomResponse\x12Y\n" +
	"\fGetMatchInfo\x12#.matchmaking.v1.GetMatchInfoRequest\x1a$.matchmaking.v1.GetMatchInfoResponseB\x1eZ\x1cmatchmaking/v1;matchmakingv1b\x06proto3"

var (
	file_matchmaking_v1_matchmaking_proto_rawDescOnce sync.Once
	file_matchmaking_v1_matchmaking_proto_rawDescData []byte
)

func file_matchmaking_v1_matchmaking_proto_rawDescGZIP() []byte {
	file_matchmaking_v1_matchmaking_proto_rawDescOnce.Do(func() {
		file_matchmaking_v1_matchmaking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matchmaking_v1_matchmaking_proto_rawDesc), len(file_matchmaking_v1_matchmaking_proto_rawDesc)))
	})
	return file_matchmaking_v1_matchmaking_proto_rawDescData
}

var file_matchmaking_v1_matchmaking_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_matchmaking_v1_matchmaking_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_matchmaking_v1_matchmaking_proto_goTypes = []any{
	(GameMode)(0),                // 0: matchmaking.v1.GameMode
	(MatchStatus)(0),             // 1: matchmaking.v1.MatchStatus
	(*CreateMatchRequest)(nil),   // 2: matchmaking.v1.CreateMatchRequest
	(*CreateMatchResponse)(nil),  // 3: matchmaking.v1.CreateMatchResponse
	(*JoinByInviteRequest)(nil),  // 4: matchmaking.v1.JoinByInviteRequest
	(*JoinByInviteResponse)(nil), // 5: matchmaking.v1.JoinByInviteResponse
	(*FindRandomRequest)(nil),    // 6: matchmaking.v1.FindRandomRequest
	(*FindRandomResponse)(nil),   // 7: matchmaking.v1.FindRandomResponse
	(*GetMatchInfoRequest)(nil),  // 8: matchmaking.v1.GetMatchInfoRequest
	(*GetMatchInfoResponse)(nil), // 9: matchmaking.v1.GetMatchInfoResponse
	(*Player)(nil),               // 10: matchmaking.v1.Player
}
var file_matchmaking_v1_matchmaking_proto_depIdxs = []int32{
	0,  // 0: matchmaking.v1.CreateMatchRequest.mode:type_name -> matchmaking.v1.GameMode
	1,  // 1: matchmaking.v1.JoinByInviteResponse.status:type_name -> matchmaking.v1.MatchStatus
	0,  // 2: matchmaking.v1.FindRandomRequest.mode:type_name -> matchmaking.v1.GameMode
	1,  // 3: matchmaking.v1.FindRandomResponse.status:type_name -> matchmaking.v1.MatchStatus
	0,  // 4: matchmaking.v1.GetMatchInfoResponse.mode:type_name -> matchmaking.v1.GameMode
	10, // 5: matchmaking.v1.GetMatchInfoResponse.players:type_name -> matchmaking.v1.Player
	1,  // 6: matchmaking.v1.GetMatchInfoResponse.status:type_name -> matchmaking.v1.MatchStatus
	2,  // 7: matchmaking.v1.MatchmakingService.CreateMatch:input_type -> matchmaking.v1.CreateMatchRequest
	4,  // 8: matchmaking.v1.MatchmakingService.JoinByInvite:input_type -> matchmaking.v1.JoinByInviteRequest
	6,  // 9: matchmaking.v1.MatchmakingService.FindRandom:input_type -> matchmaking.v1.FindRandomRequest
	8,  // 10: matchmaking.v1.MatchmakingService.GetMatchInfo:input_type -> matchmaking.v1.GetMatchInfoRequest
	3,  // 11: matchmaking.v1.MatchmakingService.CreateMatch:output_type -> matchmaking.v1.CreateMatchResponse
	5,  // 12: matchmaking.v1.MatchmakingService.JoinByInvite:output_type -> matchmaking.v1.JoinByInviteResponse
	7,  // 13: matchmaking.v1.MatchmakingService.FindRandom:output_type -> matchmaking.v1.FindRandomResponse
	9,  // 14: matchmaking.v1.MatchmakingService.GetMatchInfo:output_type -> matchmaking.v1.GetMatchInfoResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_matchmaking_v1_matchmaking_proto_init() }
func file_matchmaking_v1_matchmaking_proto_init() {
	if File_matchmaking_v1_matchmaking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matchmaking_v1_matchmaking_proto_rawDesc), len(file_matchmaking_v1_matchmaking_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matchmaking_v1_matchmaking_proto_goTypes,
		DependencyIndexes: file_matchmaking_v1_matchmaking_proto_depIdxs,
		EnumInfos:         file_matchmaking_v1_matchmaking_proto_enumTypes,
		MessageInfos:      file_matchmaking_v1_matchmaking_proto_msgTypes,
	}.Build()
	File_matchmaking_v1_matchmaking_proto = out.File
	file_matchmaking_v1_matchmaking_proto_goTypes = nil
	file_matchmaking_v1_matchmaking_proto_depIdxs = nil
}
